config/routes.rb
Rails.application.routes.draw do
 resources :todo_lists
 resources :todo_lists do
   resources :todo_tasks do
    member do
     patch :complete
    end
  end
end
  get  'pages/about'
  get 'pages/index'
  devise_for :users
  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_tasks, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true

  def self.pending_tasks
    TodoList.joins(:todo_tasks).select("todo_lists.*, todo_tasks.content as task").where(
     "todo_tasks.todo_list_id = todo_lists.id and todo_tasks.completed_at IS NULL "
     )
  end
  def self.all_todo_list_task
    TodoList.left_joins(:todo_tasks).select("todo_lists.*, todo_tasks.content as task").where(
    "todo_lists.id > 0 OR
     todo_tasks.todo_list_id = todo_lists.id"
     )
  end

  def self.all_todo_list 
    TodoList.all
  end

  def self.to_csv
  CSV.generate do |csv|
    columns = %w(id title description task)
    csv << columns.map(&:humanize)
    all_todo_list_task.each do |student|
      csv << student.attributes.values_at(*columns)
    end
  end
 end
 
end

app/models/todo_task.rb
class TodoTask < ApplicationRecord
  belongs_to :todo_list
  validates :content, presence: true
  validates :todo_list_id, presence: true
  
  def completed?
   !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:username]
  has_many :todo_lists
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache]
    added_attrs2 = [:username, :email, :password, :password_confirmation, :remember_me, :avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs2
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]
  def index
  	   # if user_signed_in?
  		  # UserNotifierMailer.welcome_email.deliver_later
  	   # end  
   #SendmailJob.perform_later
  end
 
  def new
  end

  def about
     render "user_notifier_mailer/welcome_email"
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :new, :destroy, :index, :create, :update]
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
    #@todo_l = TodoList.new(todo_list_params)
    respond_to do |format|
      format.html
      format.csv { send_data @todo_lists.to_csv, filename: "lists-#{Date.today}.csv" }
      format.pdf {render template: 'todo_lists/reporte', pdf: 'reporte', layout: 'pdf.html'}
      #SendmailJob.set(wait: 1.week).perform_later(@todo_l)
    end
     todo_lists_task = @todo_lists.pending_tasks
     @user_mail = current_user
     #UserNotifierMailer.task_email(@todo_lists_task, @user_mail).deliver_now
    # UserNotifierMailer.task_email.deliver_later
    #SendmailJob.perform_later params.permit(:todo_lists_task)[:todo_lists_task]
    #hash = @todo_lists_task.as_json
    #@user_mail.as_json.to_json
    SendmailJob.set(wait: 1.week).perform_later 
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user = current_user
  

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
	before_action :set_todo_list
	#before_action :set_todo_task, except: [:create, :update, :new]
	def index
	end
	
	def new
		@todo_task = TodoTask.new
	end

	def update
		@todo_task = @todo_list.todo_tasks.find(params[:id])
    if @todo_task.update(todo_task_params)
      flash[:success] = "Todo List item was update."
    else
      flash[:error] = "Todo List item could not be update."
    end
    redirect_to @todo_list
	end

	
	def show
	end

	def create
	 @todo_task = @todo_list.todo_tasks.create(todo_task_params)
	 redirect_to @todo_list
	end
	def destroy
	 @todo_task = @todo_list.todo_tasks.find(params[:id])
	 if @todo_task.destroy
	  flash[:success] = "Todo List task was deleted."
	 else
	  flash[:error] = "Todo List task could not be deleted."
	 end
	 redirect_to @todo_list 
	end
	def complete
	 @todo_task.update_attribute(:completed_at, Time.now)
	 redirect_to @todo_list, notice: "Todo task completed"
	end
	private
	def set_todo_list
	 @todo_list = TodoList.find(params[:todo_list_id])
	 @todo_task = params[:id] ? TodoTask.find(params[:id]) : TodoTask.new
	end
	def set_todo_task
	 @todo_task = @todo_list.todo_tasks.find(params[:id])
	 #@todo_task = params[:id] ? TodoTask.find(params[:id]) : TodoTask.new
	end
	def todo_task_params
	 params[:todo_task].permit(:content)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
  
    <%= render "shared/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

 
  <div class="container1">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title></title>
<%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<meta charset= "utf-8">
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails TODO App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      
    </p>
  </body>
</html>

app/views/pages/index.html.erb
<% provide(:title, "Index") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails TODO App</title>
  </head>
  <body>
  <div class="center jumbotron">
    <h1>TODO App</h1>
    <p>
     
    </p>
	</div>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="">
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
         <li><%= link_to 'Todo List', todo_lists_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %> 
       <ul style="width: 200px;">
      </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %>
<div class="links">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>
<!--- COMMENTED-OUT CODE -->
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>
<%= link_to "Export CSV", todo_lists_path(format: :csv) %>
<%= link_to 'Export PDF', todo_lists_path(format: :pdf)%>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/reporte.pdf.erb
<div class = "pdf">
	<h1 class="title">List and Tasks</h1>
<table class="table">
	<thead>
		<tr>
			<th>title</th>
			<th>Description</th>
			<th>Task</th>
		</tr>
		<tbody>
			<% @todo_lists.all_todo_list_task.each do |todo_list| %>
				<tr>
					 <td><%= todo_list.title %></td>
					 <td><%= todo_list.description %></td>
					 	<td><%= todo_list.task %></td>
				</tr>
			<%end%>

		</tbody>
	</thead>
</table> 
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>
<div id="todo_tasks_wrapper">
 <%= render @todo_list.todo_tasks %>
 <div id="form">
   
 </div>

 	<%= link_to 'New', new_todo_list_todo_task_path(@todo_list), :class => "btn" %>

</div>
<div class="links">
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |
	<%= link_to 'Back', todo_lists_path %>
	
</div>

app/views/todo_tasks/_form.html.erb
  <%= form_for([@todo_list, @todo_task]) do |f| %>
  	<% f.label :Tasks %> 
    <%= f.text_field :content, id: :todo_task_content, placeholder: "New Todo" %>
    <%= f.submit %>
  <% end %>

app/views/todo_tasks/_todo_task.html.erb
<div class="row clearfix">
 <% if todo_task.completed? %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
   <% end %>
  </div>
  <div class="todo_task">
   <p style="opacity: 0.4;"><strike><%= todo_task.content %></strike></p>
  </div>
  <div class="trash">
    <p><%= link_to 'Edit', edit_todo_list_todo_task_path(@todo_list, todo_task) %> </p>
   <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
    <% end %>
  </div>
 <% else %>
  <div class="complete">
    <%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
    <i class="fa fa-circle-thin"></i>
   <% end %>
  </div>
  <div class="todo_task">
   <p><%= todo_task.content %></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
  </div>
 <% end %>
</div>

app/views/todo_tasks/edit.html.erb
<h1>Edit </h1>
<%= render 'form', todo_task: @todo_task %>

app/views/todo_tasks/new.html.erb
<h1>New Todo Task</h1>

<%= render 'form', todo_task: @todo_task %>

<%= link_to 'Back', todo_lists_path %>